name: Build and push Docker image

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - name: Checkout main project
        uses: actions/checkout@v3
        with:
          submodules: true
          path: cdsi

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Docker cache
        uses: ./cdsi/.github/workflows/dockercache
        with:
          dockerdir: cdsi/c/docker
          imagename: cdsi-enclave-build

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Docker login'
        run:
          az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}

      - name: Build and push container image
        working-directory: cdsi
        run: |
          ./mvnw -e -B deploy \
            -P-build-dev-enclave \
            -Dpackaging=docker \
            -Djib.to.image="${{ secrets.REGISTRY_LOGIN_SERVER }}/cdsi:${GITHUB_REF_NAME}"
