name: Build and push Docker image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main project
        uses: actions/checkout@v3
        with:
          submodules: true
          path: cdsi

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Docker cache
        uses: ./cdsi/.github/workflows/dockercache
        with:
          dockerdir: cdsi/c/docker
          imagename: cdsi-enclave-build

      - name: Build and push container image
        working-directory: cdsi
        run: |
          ./mvnw -e -B deploy \
            -P-build-dev-enclave \
            -Dpackaging=docker \
            -Djib.to.image="${{ secrets.REGISTRY_LOGIN_SERVER }}/cdsi:${GITHUB_REF_NAME}" \
            -Djib.to.auth.username="${{ secrets.REGISTRY_USERNAME }}" \
            -Djib.to.auth.password="${{ secrets.REGISTRY_PASSWORD }}"
