name: Service CI

on: [push]

jobs:
  test-c:
    name: Build and test C
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    permissions:
      packages: read
      contents: read

    steps:
      - name: Checkout main project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          path: cdsi

      - name: Docker cache
        uses: ./cdsi/.github/workflows/dockercache
        with:
          dockerdir: cdsi/c/docker
          imagename: cdsi-enclave-build

      - name: Build and test C
        working-directory: cdsi/c
        run: make docker_all docker_tests

  valgrind-c:
    name: Valgrind C
    runs-on: ubuntu-20.04
    permissions:
      packages: read
      contents: read

    steps:
      - name: Checkout main project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          path: cdsi

      - name: Docker cache
        uses: ./cdsi/.github/workflows/dockercache
        with:
          dockerdir: cdsi/c/docker
          imagename: cdsi-enclave-build

      - name: Valgrind tests
        working-directory: cdsi/c
        run: make docker_valgrinds

  test-service:
    name: Build and test Java
    runs-on: ubuntu-20.04
    permissions:
      packages: read
      contents: read

    steps:
      - name: Checkout main project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          path: cdsi

      - name: Set up JDK 21
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Docker cache
        uses: ./cdsi/.github/workflows/dockercache
        with:
          dockerdir: cdsi/c/docker
          imagename: cdsi-enclave-build

      - name: Build and test with Maven
        working-directory: cdsi
        run: ./mvnw -e -B verify

  test-lambda:
    name: Build and test lambda
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          path: cdsi
      - name: Set up JDK 21
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: Build and test with Maven
        working-directory: cdsi/filter-cds-updates
        run: ../mvnw -e -B verify
